# Generated by Django 5.0.1 on 2024-02-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('mobile', models.BigIntegerField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
