# Generated by Django 5.0.1 on 2024-02-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentifivation', '0003_myuser_delete_myuser1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myUser',
            new_name='my_User',
        ),
    ]
