# Generated by Django 5.0.1 on 2024-02-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentifivation', '0004_rename_myuser_my_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_User',
            new_name='myUser1',
        ),
    ]
